In [3]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split


In [4]:
np.random.seed(0)

In [5]:
dogs_whisker_length=np.random.normal(loc=5,scale=1,size=10)
dogs_ear_flappiness_index=np.random.normal(loc=8,scale=1,size=10)

In [6]:
cats_whisker_length=np.random.normal(loc=8,scale=1,size=10)
cats_ear_flappiness_index=np.random.normal(loc=5,scale=1,size=10)

In [13]:
dogs_data= np.vstack((dogs_whisker_length,dogs_ear_flappiness_index)).T
cats_data= np.vstack((cats_whisker_length,cats_ear_flappiness_index)).T
data=np.vstack((dogs_data,cats_data))
labels = np.hstack((np.zeros(len(dogs_data)), np.ones(len(cats_data))))

In [14]:
X_train, X_test, y_train, y_test = train_test_split(data,labels, test_size=0.2, random_state=42)

In [15]:
X_train

array([[ 4.89678115,  8.3130677 ],
       [ 4.02272212,  8.33367433],
       [ 8.6536186 ,  5.37816252],
       [ 7.2408932 ,  8.12167502],
       [ 9.53277921,  4.61267318],
       [ 8.04575852,  6.23029068],
       [ 7.25783498,  3.01920353],
       [ 5.97873798,  8.76103773],
       [ 5.4105985 ,  7.14590426],
       [ 9.46935877,  4.69769725],
       [ 6.86755799,  8.44386323],
       [ 8.8644362 ,  4.11221425],
       [ 4.84864279,  7.79484174],
       [ 5.44701018,  5.15494743],
       [10.26975462,  4.65208785],
       [ 5.95008842,  9.49407907]])

In [16]:
X_test

array([[6.76405235, 8.14404357],
       [7.81281615, 6.20237985],
       [6.54563433, 5.15634897],
       [5.40015721, 9.45427351]])

In [18]:
y_train

array([0., 0., 1., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 1., 1., 0.])

In [20]:
def compute_error(data_dogs, data_cats, theta, theta0):
    error = 0
    for x_dog in data_dogs:
        if np.dot(theta,x_dog)+theta0 <=0:
            error+=1
    for x_cat in data_cats:
        if np.dot(theta,x_cat)+ theta0>0:
            error+=1
    return error

# Implementing random linear classifier
def random_linear_classifier(data_dogs, data_cats,k,d):
    # d is the number of features
    best_error = float('inf')
    best_theta= None
    best_theta0=None

    for _ in range(k):
        theta = np.random.normal(size=d)
        theta0=np.random.normal()
        error = compute_error(data_dogs,data_cats,theta,theta0)

        if error< best_error:
            best_error = error
            best_theta = theta
            best_theta0 = theta0
    return best_theta, best_theta0, best_error

In [23]:
k=100
d=2
best_theta_train, best_theta0_train, train_error=random_linear_classifier(X_train[y_train==0],X_train[y_train==1],k,d)

In [24]:
best_theta_train, best_theta0_train, train_error

(array([-1.18468659,  0.9606934 ]), 1.3290628465396823, 0)

In [25]:
test_error = compute_error(X_test[y_test==0], X_test[y_test==1],best_theta_train, best_theta0_train)
test_error

0

In [26]:
test_error

0